language: bash
services:
  - docker
sudo: required
branches:
  only:
    - master
script:
  # mirror
  - docker pull mcr.microsoft.com/java/jdk:8-zulu-alpine
  - docker pull mcr.microsoft.com/java/jdk:8u242-zulu-alpine	
after_success:
  #login
  - sudo docker login --username=${username}  --password=${password} registry.cn-qingdao.aliyuncs.com
  # mcr.microsoft.com/java/jdk:8-zulu-alpine
  - sudo docker tag mcr.microsoft.com/java/jdk:8-zulu-alpine registry.cn-qingdao.aliyuncs.com/jiahua/jdk:8-zulu-alpine
  # mcr.microsoft.com/java/jdk:8u242-zulu-alpine
  - sudo docker tag mcr.microsoft.com/java/jdk:8u242-zulu-alpine registry.cn-qingdao.aliyuncs.com/jiahua/jdk:8u242-zulu-alpine
  #push
  - sudo docker push registry.cn-qingdao.aliyuncs.com/jiahua/jdk:8-zulu-alpine
  - sudo docker push registry.cn-qingdao.aliyuncs.com/jiahua/jdk:8u242-zulu-alpine	